-- ITEMS
CREATE TABLE IF NOT EXISTS items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sku TEXT UNIQUE,
  name TEXT NOT NULL,
  category TEXT,
  price REAL NOT NULL DEFAULT 0,
  display_group TEXT,
  size_label TEXT,
  allow_flavors INTEGER NOT NULL DEFAULT 0,
  pos_sort_order INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1
);

-- COMPONENTS
CREATE TABLE IF NOT EXISTS components (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  qty_used REAL DEFAULT 0,
  unit_cost REAL DEFAULT 0,
  pos_track_sellout INTEGER DEFAULT 0
);

-- RECIPES
CREATE TABLE IF NOT EXISTS recipes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  item_id INTEGER NOT NULL,
  component_id INTEGER NOT NULL,
  qty_per_item REAL NOT NULL DEFAULT 0,
  FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
  FOREIGN KEY (component_id) REFERENCES components(id) ON DELETE CASCADE,
  UNIQUE (item_id, component_id)
);

-- INVENTORY (the warehouse-level stock)
CREATE TABLE IF NOT EXISTS inventory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  unit TEXT,
  case_cost REAL DEFAULT 0,
  units_per_case REAL DEFAULT 0,
  qty_on_hand REAL DEFAULT 0,
  reorder_point REAL DEFAULT 0,
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts TEXT NOT NULL,
  cashier TEXT NOT NULL,
  method TEXT NOT NULL,
  discount REAL NOT NULL DEFAULT 0,
  discount_type TEXT, 
  tax REAL NOT NULL DEFAULT 0,
  subtotal REAL NOT NULL DEFAULT 0,
  total REAL NOT NULL DEFAULT 0,
  cash_given REAL DEFAULT 0,
  change_given REAL DEFAULT 0,
  receipt_date TEXT,
  receipt_seq INTEGER,
  shift_id INTEGER,  -- REQUIRED so FK works
  FOREIGN KEY (shift_id) REFERENCES shifts(id)
);


-- ORDER LINES
CREATE TABLE IF NOT EXISTS order_lines (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  order_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  qty REAL NOT NULL DEFAULT 0,
  unit_price REAL NOT NULL DEFAULT 0,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES items(id)
);

-- SHIFTS
CREATE TABLE IF NOT EXISTS shifts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts_start TEXT NOT NULL,
  ts_end TEXT,
  cashier TEXT NOT NULL,
  opening_float REAL NOT NULL DEFAULT 0,
  closing_amount REAL,
  over_short REAL,
  is_active INTEGER NOT NULL DEFAULT 1
);

-- EXPENSES (optional)
CREATE TABLE IF NOT EXISTS expenses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL,
  category TEXT,
  amount REAL NOT NULL DEFAULT 0,
  memo TEXT
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS admin_pins (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pin TEXT NOT NULL,
  label TEXT,
  active INTEGER NOT NULL DEFAULT 1
);

-- TILL COUNTS
CREATE TABLE IF NOT EXISTS till_counts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shift_id INTEGER NOT NULL,
  count_type TEXT NOT NULL,
  hundreds INTEGER NOT NULL DEFAULT 0,
  fifties INTEGER NOT NULL DEFAULT 0,
  twenties INTEGER NOT NULL DEFAULT 0,
  tens INTEGER NOT NULL DEFAULT 0,
  fives INTEGER NOT NULL DEFAULT 0,
  ones INTEGER NOT NULL DEFAULT 0,
  quarters INTEGER NOT NULL DEFAULT 0,
  dimes INTEGER NOT NULL DEFAULT 0,
  nickels INTEGER NOT NULL DEFAULT 0,
  pennies INTEGER NOT NULL DEFAULT 0,
  total REAL NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now', '-6 hours')),
  FOREIGN KEY (shift_id) REFERENCES shifts(id)
);


-- POS FLAVORS / PUMP MODIFIERS
CREATE TABLE IF NOT EXISTS flavors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  price_per_pump REAL NOT NULL DEFAULT 0.25,
  active INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0
);
